### ISSUE TITLE
Bus Routes Overlaying

### ISSUE THREAD

**Issue by netothong** [cheeaun/busrouter-sg#1]
The ability to view a bus route in Google Map is very informative. But wouldn't it be outstanding if you are able to choose three bus service number and "busrouter-sg" will HIGHLIGHT the bus stops that is COMMON (the two or three buses will stop at the same bus stop) to them.

Rationale: Let us assume that you want to go from Point A to Point B, and you want to know what are your choices and the fastest route to reach Point B. And we want to know at which bus stop(s) will these two or three service numbers will be common. This will allow us to plan our routes more efficiently as we might want to stop over a certain place and the "busrouter-sg" will inform us that if the bus number you were in just now had already passed by the time you came back to the bus stop you alighted, you will still be able to catch up the other two service numbers.

**Comment by tianqig** [comment]
It would be great to be able to show multiple bus routes at the same time so viewers be able to figure out how  to change bus at what bus stops in order to optimize their travel. 

Not sure if the current version can do the trick or not. Seems to me I can only choose one bus at a time, not able to select multiple buses. Although I can select one bus a time, then choose another one, then I need to mentally figure out where the bus routes would meet, etc. It's troublesome.

**Comment by yEngineer7** [comment]
I'm quite interested to see this too. Oftentimes it would be helpful to find the coverage of the buses from the interchange (in a particular colour) as well as from the nearest bus stop outside for passing services (in a different colour).

**Comment by cheeaun** [comment]
Closing this. Multi-route mode is now available e.g.: https://busrouter.sg/#/services/117~169~883

If this feature doesn't work as expected, feel free to open another issue.
