### ISSUE TITLE
Unintuitive sorting behaviour

### ISSUE THREAD

**Issue by bnjmnt4n** [cheeaun/busrouter-sg#28]
Previously, the bus services were sorted by the main service number in ascending order, but currently they are grouped together based on the first digit of the service number. This might be unexpected by people scrolling through the list.

**Comment by cheeaun** [comment]
That's a good observation :)

I've been trying out both sort orders for the past few months and concluded a few things:

1. Visually speaking, bus service numbers are aligned left instead of right, unlike most number stuff that we deal with everyday. The other reason is that some numbers have alphabets e.g. `851e` which makes alignment a bit messy.
2. From an use-case perspective, I suspect most people already have a number in mind and would skim them immediately from the list of numbers.
3. Judging from (1) and (2) above, if you are trying to find a bus number `133`, skimming means you'll be looking at the first number `1` in the list, then only fill up the `33` (assuming that we all read left-to-right).

You can try it out here https://www.transitlink.com.sg/eservice/eguide/service_idx.php

![screenshot 2018-11-22 at 12 38 13 pm](https://user-images.githubusercontent.com/2296/48882177-ea930500-ee53-11e8-8daf-5237af46b522.png)

Sorting numbers in ascending order may seem logical but doesn't help when it comes to skimming through them. My goal is to make skimming easy for everyday usage. Personally I was frustrated to find my bus number with the logical ascending order 😅 

This is merely my observation & speculation for now. I might change this again if I get more feedback on this 😄

**Comment by bnjmnt4n** [comment]
Thanks for the explanation - seems logical and well thought out. Guess you should get more feedback before changing anything.

**Comment by cheeaun** [comment]
Closing this for now, until I get more feedback on this 😬
