### ISSUE TITLE
Geo data for bus stops

### ISSUE THREAD

**Issue by janakagamini** [cheeaun/busrouter-sg#9]
Hi,

Where did you get the geo data (lat, long) for the bus stops?

Nice work by the way,
Janaka

**Comment by cheeaun** [comment]
As mentioned in the [README](https://github.com/cheeaun/busrouter-sg#readme), all data comes from http://mytransport.sg/

Here are the scripts that scrape the data: https://github.com/cheeaun/busrouter-sg/tree/master/tasks

**Comment by janakagamini** [comment]
Thanks for the response

From the readme I thought you meant the data is from the [mytransport.sg API](http://www.mytransport.sg/content/dam/mytransport/DataMall_StaticData/LTA_DataMall_API_User_Guide.pdf), and there was no mention of lat,long there, so was a bit confused.

Anyways, from the scripts it seems like the lat, long comes from streetdirectory?

Thanks.

**Comment by cheeaun** [comment]
If you're referring to the bus stop coordinates, the LTA datamall does provide the data in 'shp' (static data) format http://www.mytransport.sg/content/mytransport/home/dataMall.html

For busrouter-sg app, I don't use that because the data is not updated and missing a few bus stops. Instead, I scrape them from the web site via this script: https://github.com/cheeaun/busrouter-sg/blob/master/tasks/fetch-bus-stops-routes.js

**Comment by janakagamini** [comment]
Understood, thanks for clarifying!
